### ISSUE TITLE
SuperTracker and Parser should have class label in sequence diagram

### ISSUE THREAD

**Issue by awesomesjh** [AY2324S2-CS2113-T13-4/tp#68]
Correct me if I'm mistaken, but I believe that SuperTracker and Parser should have class label in the sequence diagram in Parser.puml.
The methods called are class level methods, SuperTracker and Parser are not instances of objects.

**Comment by rismm** [comment]
It looks like I have indeed made a mistake and you are right. Thanks for bringing this to my attention, I will make the necessary corrections soon.
