### ISSUE TITLE
Code Review for Timothy

### ISSUE THREAD

**Issue by sevenseasofbri** [AY2324S2-CS2113-T13-4/tp#90]
Reviewed some files for @TimothyLKM

In `Ui.java`:

- [x] Function names should ideally be verbs and not nouns. So the functions like `listSize`, `priceMessage`, `quantityMessage` and `newItemOpening` should be `getListSize`, `getPriceMessage`, `getQuantityMessage` and `getNewItemOpening` instead. Many functions in this class have been named this way, so you might want to fix that.
- [x] Same with `foundItem` and `noItemFound`, it should be `printFoundItem` & `printNoItemFound` respectively

**Comment by TimothyLKM** [comment]
Thank you for the comments, i've edited the UI methods to be verbs and not nouns.
